### ISSUE TITLE
Is jourmail.com functional?

### ISSUE THREAD

**Issue by auxiliary** [shime/journmail#27]
Is the project in a usable status at the moment. I receive emails, but there's no link to history or streak, or logging in, or anything anywhere.

**Comment by shime** [comment]
Yup it is, but it's in alpha. You'll receive a link to history on your next email, once you have something in your history.

If you're impatient the link is `https://journmail.com/history/<your-uuid>`. Your UUID can be found out from the unsubscribe link.
